### ISSUE TITLE
No results found for the query:

### ISSUE THREAD

**Issue by ThomasKoscheck** [Areeb-M/GoogleAnswers#1]
Hi there,
this is a really cool script! Sadly it returns always _No results found for the query: xyz_
I think something needs to be fixed there. 
Hope you can find a solution

Kind regards

**Comment by Areeb-M** [comment]
Hello Thomas,
thanks for taking notice of my script! 

I'm afraid that the problem you're running into isn't a fault of the script, but rather that it is outside of the scope of the script.

The main purpose of my script is to retrieve the information displayed in Featured Snippets during a google search. Featured Snippets are those specialized text boxes at the top of the results page that provide answers to your query. Examples include:
<img width="900" alt="radius of mars" src="https://user-images.githubusercontent.com/7026766/33530791-7b0609dc-d84a-11e7-8820-250f8502aa23.PNG">
and
<img width="899" alt="time in tokyo" src="https://user-images.githubusercontent.com/7026766/33530792-80751e30-d84a-11e7-8e4e-f05524f48d00.PNG">
with the target being circled in red.

On the other hand, googling "xyz" returns no similar Featured Snippet.
<img width="908" alt="xyz" src="https://user-images.githubusercontent.com/7026766/33530822-bb808988-d84a-11e7-8341-bb397aafa965.PNG">

That's the reason the script returns <i>No results found for query: xyz</i>

However, search results ARE based on locale, and what shows up for you won't necessarily show up for me. So if you do see a Featured Snippet, I'd be happy to take a look and see how to include it in the script.

**Comment by ThomasKoscheck** [comment]
Hey, 
sorry for the misunderstanding. xyz was meant as an placeholder for questions.

I tried it with german questions; google shows featured snippets but your script doesnt returned anything.

However, your answer led to an idea: Is it possible that  I need to change the "browser string" in Scraper.py, to find results to german questions?

Thanks for the huge answer!

**Comment by ThomasKoscheck** [comment]
Hey, 
I debugged the script and found the following.
It seems, that google changed there answerfile.

I changed in Scraper.py the following: 
```
def scrape(url):
    global HEADER_PAYLOAD, TARGET_LIST
    data = requests.get(url, headers=HEADER_PAYLOAD).text 
    start_js = data.index('/g-section-with-header') #change
    data = data[0:start_js]
    results = []

    for target in TARGET_LIST:
        results += Parser(target).feed(data)

    return results
```

Now it works fine

**Comment by Areeb-M** [comment]
I haven't maintained this script for a few months so google changed their results since then. It would be nice if you could create a pull request to incorporate the change into the script.

Thanks for finding a simple solution to the problem.
